# Generated by Django 5.2.6 on 2025-10-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='默认配置', max_length=100)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('base_url', models.CharField(default='https://api.aihubmix.com/v1', max_length=255)),
                ('model_name', models.CharField(default='gpt-3.5-turbo', max_length=100)),
                ('embedding_model', models.CharField(default='text-embedding-ada-002', max_length=100)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=2000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI配置',
                'verbose_name_plural': 'AI配置',
            },
        ),
    ]
